[PROJECT]
Format=ASM11

[ASM11]
Case Sensitive=0
Listing=0
Map=0
S19=1
Xtra=1
Rel=1
RTS=0
Show progress=1
Sym=1
P1 Stop=1
Over/Mem=1
S0 header=0
Spaces=0
Warn=1
Include Dir=

[CPU]
Type=M68HC(7)11E9
XTAL=8 MHz
BPROT0=1
BPROT1=1
BPROT2=1
BPROT3=1
TMSK2=0
IRQ=0
RMem=D000 FFFF
RWMem=0000 01FF
IOMem=B600 B7FF
Random Memory=1

[FILES]
Count=1
File0=Frame.asm

[FORMS]
ProForm=0 210 180 652 0
ProFormTab=TabFiles
EditorForm=-4 110 346 648 2

[WATCH]
Count=0
